#!/bin/sh

DIR=test
cd ../ && maude < teleport.maude -no-banner -no-advise | sed -r '/^(rewrites:|Solution|states:)/d' > $DIR/teleport.out
# diff $DIR/teleport.expected teleport.out > /dev/null 2>&1
diff $DIR/teleport.expected $DIR/teleport.out
rm $DIR/teleport.out